### ISSUE TITLE
Add possiblity to use Token Counting API

### ISSUE THREAD

**Issue by Richard-Weiss** [lugia19/Claude-Usage-Extension#2]
It would be useful to be able to use the [Token counting API](https://docs.anthropic.com/en/docs/build-with-claude/token-counting) for more accurate token counting.

**Comment by lugia19** [comment]
I have thought about this - the problem is that there is no easy way to do it.

I don't want to include my API key in the extension (for obvious reasons) and I can't just have the extension send the text to a server on my end that calls the token counting API (for privacy).

**Comment by Richard-Weiss** [comment]
Yeah, I meant the second option being BYOK.
I can implement that, just made the issue for tracking and stuff.

**Comment by lugia19** [comment]
I just don't think it's really worth implementing? For text, the estimate is very close, even at high text lengths.

Meanwhile, for PDFs and images, it would mean having to download and send them to the endpoint to get token counts, which... is its own whole thing. Just doesn't feel worth doing, with all these caveats, imo.

**Comment by lugia19** [comment]
Apparently the estimate is a lot less close in non-english languages, so I'm going to try and implement this.

I'll implement it for text, images and PDFs, with caching for images and PDFs to avoid re-uploading files every time.

**Comment by lugia19** [comment]
Implemented.
